spring.application.name=url-shortner-sb

# Enable H2 console
spring.h2.console.enabled=true

# Optional: customize path (default is /h2-console)
spring.h2.console.path=/h2-console

# JDBC URL for in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true

# JPA
spring.jpa.hibernate.ddl-auto=update

jwt.secret=asxasdhbauedwutefdtwyuegdytwefdytwfe
jwt.expiration=172800000